---
# doing configuration

- name: setting up vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{general.local_home}}/.local/share/nvim/site/autoload/plug.vim"
  




